// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umrzylmqnizppgazxuec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtcnp5bG1xbml6cHBnYXp4dWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTg5NTMsImV4cCI6MjA2NDU5NDk1M30.Qqx0vWG2OryiaovT_7LmoOynfyuqEriDzEYVhFwzF0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);